version: '3.8'

services:
  mysql:
    container_name: vstream-catalog-admin-mysql
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=vstream-catalog-admin
    security_opt:
      - seccomp:unconfined
    ports:
      - "3306:3306"
    networks:
      - vstream-catalog-admin-network

networks:
  vstream-catalog-admin-network: